---
title: "Stratigraphic diagrams with tidypaleo"
author: "Dewey Dunnington"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Stratigraphic diagrams with tidypaleo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.height = 3,
  fig.width = 5,
  dpi = 150
)
```

```{r}
library(tidypaleo)
library(ggplot2)
theme_set(theme_bw())
```

## Geochemical stratigraphic plots

```{r}
data("alta_lake_geochem")
alta_lake_geochem
```

```{r}
ggplot(alta_lake_geochem, aes(x = value, y = depth)) +
  geom_path() +
  geom_point() +
  scale_y_reverse() +
  facet_wrap(~param, scales = "free_x", nrow = 1) +
  rotated_axis_labels()
```

```{r}
alta_adm <- age_depth_model(
  alta_lake_bacon_ages, 
  depth = depth_cm,
  age = 1950 - age_weighted_mean_year_BP
)

ggplot(alta_lake_geochem, aes(x = value, y = depth)) +
  geom_path() +
  geom_point() +
  scale_y_depth_age(alta_adm) +
  facet_wrap(~param, scales = "free_x", nrow = 1) +
  rotated_axis_labels()
```

## Species abundance stratigraphic plots

```{r}
data("keji_lakes_plottable")
keji_lakes_plottable
```

```{r, fig.height=6}
ggplot(keji_lakes_plottable, aes(x = rel_abund, y = depth)) +
  geom_col_segsh() +
  scale_y_reverse() +
  facet_abundanceh(vars(taxon), grouping = vars(location))
```

```{r}
ggplot(halifax_lakes_plottable, aes(x = rel_abund, y = location, fill = sample_type)) +
  geom_colh(width = 0.5, position = "dodgev") +
  facet_abundanceh(vars(taxon))
```
