on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install libgit2
        run: brew install libgit2
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "systemfonts"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package site
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
